export const rows = [
  {
    id: 1,
    product: "Wireless Mouse",
    img: "https://via.placeholder.com/50",
    customer: "John Doe",
    date: "2025-10-31",
    amount: 25.99,
    method: "Credit Card",
    status: "Approved",
  },
  {
    id: 2,
    product: "Bluetooth Headphones",
    img: "https://via.placeholder.com/50",
    customer: "Jane Smith",
    date: "2025-10-30",
    amount: 79.5,
    method: "PayPal",
    status: "Pending",
  },
  {
    id: 3,
    product: "Mechanical Keyboard",
    img: "https://via.placeholder.com/50",
    customer: "Alice Johnson",
    date: "2025-10-28",
    amount: 120.0,
    method: "Credit Card",
    status: "Declined",
  },
  {
    id: 4,
    product: "USB-C Hub",
    img: "https://via.placeholder.com/50",
    customer: "Bob Williams",
    date: "2025-10-27",
    amount: 45.0,
    method: "Debit Card",
    status: "Approved",
  },
  {
    id: 5,
    product: "Gaming Chair",
    img: "https://via.placeholder.com/50",
    customer: "Charlie Brown",
    date: "2025-10-26",
    amount: 299.99,
    method: "Credit Card",
    status: "Pending",
  },
  {
    id: 6,
    product: "Laptop Stand",
    img: "https://via.placeholder.com/50",
    customer: "Diana Prince",
    date: "2025-10-25",
    amount: 39.99,
    method: "PayPal",
    status: "Approved",
  },
  {
    id: 7,
    product: "Smartphone Case",
    img: "https://via.placeholder.com/50",
    customer: "Ethan Hunt",
    date: "2025-10-24",
    amount: 15.0,
    method: "Credit Card",
    status: "Declined",
  },
  {
    id: 8,
    product: "Portable Charger",
    img: "https://via.placeholder.com/50",
    customer: "Fiona Gallagher",
    date: "2025-10-23",
    amount: 22.5,
    method: "Debit Card",
    status: "Approved",
  },
  {
    id: 9,
    product: "Webcam",
    img: "https://via.placeholder.com/50",
    customer: "George Martin",
    date: "2025-10-22",
    amount: 55.0,
    method: "Credit Card",
    status: "Pending",
  },
  {
    id: 10,
    product: "Desk Lamp",
    img: "https://via.placeholder.com/50",
    customer: "Hannah Lee",
    date: "2025-10-21",
    amount: 34.99,
    method: "PayPal",
    status: "Approved",
  },
];